**Difference between Module,Package and Library**

Module: single function(add,area)

Package: Combination of multiple module (math,plot)

Libray: Combination of module and package




# Numpy (Numarical data)

-used for Numarical Function

-Supports to Array, Matrics amd matmatical Functions

-N-Dimensional
-Sinulation and random Sampling


In [3]:
# Installation

#!pip install numpy

In [49]:
# Creating Array

import numpy as np
# one Dimension Array
array1 = np.array([1,2,3,4,5,6])
print(array1)

#2D Array
array2 = np.array([[1,2,3],[4,5,6]])
print(array2)

#Zero array
array3 = np.zeros((3,3))
print(array3)


#ones array
array5 = np.ones((3,3))
print(array5)

#Random array
array4 = np.random.random((3,3))
print(array4)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.05889731 0.37121668 0.11313375]
 [0.47328847 0.17592827 0.60143427]
 [0.89403349 0.4320121  0.20007318]]


In [51]:
# Array attributes: Size,Shape, Data Types

# Shape
print(array1.shape)

# Size
print(array1.size)

#Data Type
print(array1.dtype)

(6,)
6
int32


Number :  int,float,deci, bigint

Characters : strings, object  

In [53]:
#Indexing (0 to 10 its print 0 to 9 only)
print(array1)
print(array1[3])


[1 2 3 4 5 6]
4


In [32]:
#slicing (start:stop:step)
print(array1)
print(array1[3])
print(array1[0:4])
print(array1[0:6:2])

[1 2 3 4 5 6]
4
[1 2 3 4]
[1 3 5]


create 2, one dimensional array perform addition subtraction multiplication and division


In [63]:
a = np.array([10,20,30,40])
b = np.array([50,60,70,80])
# Perform addition
addition = a + b
print(addition)

[ 60  80 100 120]


In [67]:
# Perform subtraction
subtraction = a - b
print(subtraction)

[-40 -40 -40 -40]


In [73]:
# Perform multiplication
multiplication = a * b
print(multiplication)

[ 500 1200 2100 3200]


In [75]:
# Perform division
division = a / b
print(division)

[0.2        0.33333333 0.42857143 0.5       ]


In [83]:
!pip install pandas

In [85]:
# Create a Data Frame
import pandas as pd



In [89]:
#Create a Data
data = {'Name': ['Alice','Bob','Cyan','Roon','Kayne'],
        'Age' : [23,24,25,26,21],
        'City' : ['New York','Chicago','Houston','Phoenix','Los Angeles']}
print(data)

df = pd.DataFrame(data)
print(df)

{'Name': ['Alice', 'Bob', 'Cyan', 'Roon', 'Kayne'], 'Age': [23, 24, 25, 26, 21], 'City': ['New York', 'Chicago', 'Houston', 'Phoenix', 'Los Angeles']}
    Name  Age         City
0  Alice   23     New York
1    Bob   24      Chicago
2   Cyan   25      Houston
3   Roon   26      Phoenix
4  Kayne   21  Los Angeles


In [91]:
# View top rows

df.head(2)

Name  Age      City
0  Alice   23  New York
1    Bob   24   Chicago

In [93]:
df.tail(2)

Name  Age         City
3   Roon   26      Phoenix
4  Kayne   21  Los Angeles

In [97]:
#view the Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    5 non-null      object
 1   Age     5 non-null      int64 
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes


In [101]:
#single column
print(df['City'])

#multiple column
print(df[['Name','City']])

0       New York
1        Chicago
2        Houston
3        Phoenix
4    Los Angeles
Name: City, dtype: object
    Name         City
0  Alice     New York
1    Bob      Chicago
2   Cyan      Houston
3   Roon      Phoenix
4  Kayne  Los Angeles


In [105]:
#Rows by index
print(df.iloc[2])

#Rows by Label
print(df.loc[2])

Name       Cyan
Age          25
City    Houston
Name: 2, dtype: object
Name       Cyan
Age          25
City    Houston
Name: 2, dtype: object


In [107]:
#modifying the age
df['Age'] = df['Age'] + 2
print(df)


    Name  Age         City
0  Alice   25     New York
1    Bob   26      Chicago
2   Cyan   27      Houston
3   Roon   28      Phoenix
4  Kayne   23  Los Angeles


In [111]:
#check for missing value
print(df.isnull().sum())


print(df.dropna())

Name    0
Age     0
City    0
dtype: int64
    Name  Age         City
0  Alice   25     New York
1    Bob   26      Chicago
2   Cyan   27      Houston
3   Roon   28      Phoenix
4  Kayne   23  Los Angeles


In [115]:
#to save data

df.to_csv('data.csv', index = False)

In [119]:
#Load the data
new_data = pd.read_csv(r'C:\Users\aswin\data.csv')
print(new_data)

    Name  Age         City
0  Alice   25     New York
1    Bob   26      Chicago
2   Cyan   27      Houston
3   Roon   28      Phoenix
4  Kayne   23  Los Angeles
